apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: ${APPLICATION_NAME}
labels:
  template: ${APPLICATION_NAME}-template
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: ${APPLICATION_NAME}
    namespace: ca94a8-prod
    labels:
      app: citz-imb-slam-api
      app.kubernetes.io/component: ${APPLICATION_NAME}
      app.kubernetes.io/instance: ${APPLICATION_NAME}
      app.kubernetes.io/name: ${APPLICATION_NAME}
      app.kubernetes.io/part-of: citz-imb-slam
    annotations:
      app.openshift.io/connects-to: >-
        [{"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","name":"postgresql"}]
      app.openshift.io/vcs-ref: ''
      app.openshift.io/vcs-uri: 'https://github.com/bcgov/citz-imb-slam-api'
      openshift.io/generated-by: OpenShiftWebConsole
  spec:
    ports:
      - name: 3000-tcp
        protocol: TCP
        port: 3000
        targetPort: 3001
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    type: ClusterIP
    sessionAffinity: None
    ipFamilies:
      - IPv4
    ipFamilyPolicy: SingleStack
  status:
    loadBalancer: {}
parameters:
- description: Application Name
  displayName: AppName
  name: APPLICATION_NAME
  required: true
  value: citz-imb-slam-api
