version: '3.8'
services:
###############################################################################
###                       POSTGRES DB Container                             ###
###############################################################################
  slam-db:
    container_name: slam-db
    image: postgres:14.2-alpine3.15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
###############################################################################
###                              SLAM API                                   ###
###############################################################################
  slam-api:
    container_name: slam-api
    build:
      context: .
    ports:
      - 3000:3000
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SYNCHRONIZE=${POSTGRES_SYNCHRONIZE}
