version: '3.8'
services:
    ###############################################################################
    ###                       POSTGRES DB Container                             ###
    ###############################################################################
    postgres:
        container_name: postgres
        image: postgres:10.21-alpine3.16
        restart: always
        networks:
            - slam-net
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-snowball}
            - POSTGRES_USER=${POSTGRES_USER:-postgres}
            - POSTGRES_DB=${POSTGRES_DB:-slam_db}
        command: ['postgres', '-c', 'logging_collector=on']

    ###############################################################################
    ###                       POSTGRES ADMIN DB Container                       ###
    ###############################################################################
    pg-admin:
        container_name: pg-admin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - '${PGADMIN_PORT:-5050}:80'
        networks:
            - slam-net
        restart: unless-stopped

    ###############################################################################
    ###                              SLAM API                                   ###
    ###############################################################################
    slam-api:
        container_name: slam-api
        build:
            context: .
        networks:
            - slam-net
        ports:
            - 3001:3001
        environment:
            - POSTGRES_USER=${POSTGRES_USER:-postgres}
            - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
            - POSTGRES_DB=${POSTGRES_DB:-slam_db}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-snowball}
            - POSTGRES_SYNCHRONIZE=${POSTGRES_SYNCHRONIZE:-true}
        volumes:
            - ./citz-imb-slam-api:/src/
            - nodemodules:/node_modules
        depends_on:
            - postgres
        command: ['npm', 'run', 'dev']

    ###############################################################################
    ###                              KeyCloak                                   ###
    ###############################################################################
    keycloak:
        container_name: keycloak
        image: docker.io/bitnami/keycloak:16
        networks:
            - slam-net
        depends_on:
            - postgres
        ports:
            - 80:8080
        environment:
            - KEYCLOAK_DATABASE_HOST=${POSTGRES_HOST:-postgres}
networks:
    slam-net:
        driver: 'bridge'

volumes:
    postgres:
    pgadmin:
    nodemodules: {}
