version: '3.8'
services:

###############################################################################
###                       POSTGRES DB Container                             ###
###############################################################################
  postgres:
    container_name: postgres
    image: postgres:14.2-alpine3.15
    restart: always
    networks:
      - slam-net
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-snowball}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-slam-db}
    command: ["postgres", "-c", "logging_collector=on"]

###############################################################################
###                       POSTGRES ADMIN DB Container                       ###
###############################################################################
  pgadmin:
    container_name: pg-admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - slam-net
    restart: unless-stopped

###############################################################################
###                              SLAM API                                   ###
###############################################################################
  slam-api:
    container_name: slam-api
    build:
      context: .
    networks:
      - slam-net
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-slam-db}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-snowball}
      - POSTGRES_SYNCHRONIZE=${POSTGRES_SYNCHRONIZE:-true}
    depends_on:
      - postgres
    command: ["npm", "run", "dev:watch"]  

networks:
  slam-net:
    driver: "bridge"

volumes:
    postgres:
    pgadmin:
