apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: deploy-db-template
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: slam-db-deployment
      namespace: ${NAMESPACE}
      labels:
        component: slam-db
    spec:
      replicas: 1
      selector:
        matchLabels:
          component: slam-db
      template:
        metadata:
          labels:
            component: slam-db
        spec:
          volumes:
            - name: slam-db-storage
              persistentVolumeClaim:
                claimName: slam-db-persistent-volume-claim
          containers:
            - name: slam-db
              image: 'postgres:14.2-alpine3.15'
              ports:
                - containerPort: 5432
              volumeMounts:
                - name: slam-db-storage
                  mountPath: /var/lib/postgresql
                  subPath: postgres
              env:
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: slam-db
                      key: POSTGRES_PASSWORD
                - name: POSTGRES_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: slam-db
                      key: POSTGRES_DATABASE
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: slam-db
                      key: POSTGRES_USER

  - kind: Service
    apiVersion: v1
    metadata:
      name: slam-db-service
      namespace: '${NAMESPACE}'
    spec:
      type: ClusterIP
      selector:
        component: slam-db
      ports:
        - port: 5432
          targetPort: 5432

  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: slam-db-persistent-volume-claim
      namespace: ${NAMESPACE}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

parameters:
  - name: NAMESPACE
    displayName: Namespace
    required: true
