name: CICD SLAM-API

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: citz-imb-slam-api-CICD
  cancel-in-progress: false

jobs:
  commit-data:
    runs-on: ubuntu-20.04
    outputs:
      short_sha: ${{ steps.commit-data.outputs.short_sha }}
    steps:
      - name: Checkout Action
        uses: actions/checkout@v2
      - name: Get commit short_sha
        id: commit-data
        uses: redhat-actions/common/commit-data@v1

  build:
    needs: commit-data
    uses: bcgov/citz-imb-slam-api/.github/workflows/build.yml@main
    with:
      SHORT_SHA: ${{ needs.commit-data.outputs.short_sha }}
    secrets:
      CACHE_VERSION: ${{ secrets.CACHE_VERSION }}

  deploy-dev:
    name: Deploy Dev
    needs: [commit-data, build]
    uses: bcgov/citz-imb/.github/workflows/Deploy.yml@main
    with:
      ENVIRONMENT: dev
      TAG: ${{ needs.commit-data.outputs.short_sha}}
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}
      TEAM_HOOK: ${{ secrets.TEAM_HOOK }}
